version: '2'
services:
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    depends_on:
      - zoo1
      - zoo2

    ports:
      - "9092:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: trans:1:2
      KAFKA_ADVERTISED_HOST_NAME: 167.71.235.115
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    depends_on:
      - zoo1
      - zoo2
      
    ports:
      - "9093:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 167.71.235.115
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181
  zoo1:
    image: elevy/zookeeper:latest
    container_name: zookeeper1
    environment:
      MYID: 1
      SERVERS: zoo1,zoo2
    ports:
      - "2181:2181"
      - "2888"
      - "3888"
  zoo2:
    image: elevy/zookeeper:latest
    container_name: zookeeper
    environment:
      MYID: 2
      SERVERS: zoo1,zoo2
    ports:
      - "2182:2181"
      - "2888"
      - "3888"
  producer:
    image: producer/java:latest
    container_name: producer
    build:
     context: ./Producer
    depends_on:
      - kafka1
      - kafka2

